import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../utils/cn";
import {
  FontPressStarter2P,
  FontRubik,
  FontRubikItalic,
} from "../utils/load-fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={cn(
          FontPressStarter2P.variable,
          FontRubik.variable,
          FontRubikItalic.variable
        )}
      >
        <div className="overflow-x-hidden bg-black ">{children}</div>
      </body>
    </html>
  );
}
